### ISSUE TITLE
Screenshots ohne Schatten

### ISSUE THREAD

**Issue by ghost** [RobinTheHood/module-loader.de#2]
Ich schlage vor den Schatten der Screenshots (wie bei dem YouTube Screenshot) auf der Landing page zu entfernen und mit CSS zu erstellen. Somit sieht der Schatten besser aus und das Auge wird meiner Meinung nach besser durch die Seite geführt. Wir können dann flexibel mit CSS entscheiden, ob die Bilder einheitlich mit dem Text oder ein- oder ausgerückt dargestellt werden sollen.

![image](https://user-images.githubusercontent.com/44577029/88061833-51584c80-cb68-11ea-95b8-7c78089f233d.png)

**Comment by RobinTheHood** [comment]
Finde ich eine sehr gute Idee. :-) Möchtest du das übernehmen oder ist das nur ein Vorschlag? :-)

**Comment by ghost** [comment]
Ich kann nicht so fancy Mac screenshots machen, gibt es da ein tool für?

**Comment by RobinTheHood** [comment]
Ich würde vorschlagen vielleicht mit Photoshop etc den Schatten aus den bestehenden Bildern zu entfernen. Bei Mac wird da auch immer automatisch der Schatten beim erstellen eines Screenshots gemacht. Sonst könnte ich die Bilder vorbereiten und du machst das CSS?

**Comment by ghost** [comment]
Klingt gut 👍

**Comment by RobinTheHood** [comment]
Wurde mit PullRequest #3 umgesetzt.
